"""Adicionado campo currency a person

Revision ID: 08b4f77ef470
Revises: 1cbe81ddd146
Create Date: 2022-09-10 15:27:09.203369

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '08b4f77ef470'
down_revision = '1cbe81ddd146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('curruency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'curruency')
    # ### end Alembic commands ###
