"""Corrigido erro de digitação no nome do campo currency da classe Person

Revision ID: 3a2123504483
Revises: 08b4f77ef470
Create Date: 2022-09-10 15:37:59.951434

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3a2123504483'
down_revision = '08b4f77ef470'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('person', 'curruency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('curruency', sa.VARCHAR(), nullable=True))
    op.drop_column('person', 'currency')
    # ### end Alembic commands ###
